services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: user-service:local
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./swagger
    command: node dist/server.js
