version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: user-service:dev-local
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start-dev
